import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Pergunte ao Pato!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body >
        <AppProvider>
          {children}
        </AppProvider>
        <Footer />
      </body>
    </html>
  );
}
